{{- define "common.secretproviderclassfiles" -}}
{{- $common := dict "Values" .Values.common -}}
{{- $noCommon := omit .Values "common" -}}
{{- $overrides := dict "Values" $noCommon -}}
{{- $noValues := omit . "Values" -}}
{{- with merge $noValues $overrides $common -}}
{{- if .Values.secretsStoreCsi.files.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "secretStoreCSISecretNameFiles" $ }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  provider: aws
  parameters:
    objects: |
      {{- range .Values.secretsStoreCsi.files.objects }}
      - objectName: {{ .name | quote }}
        objectType: "secretsmanager"
        objectAlias: {{ .alias | quote }}
      {{- end }}
{{- end }}
{{- end }}
{{- end }}